version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: pg-boss
    versions:
    - 5.0.8
    - 5.1.0
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: moleculer
    versions:
    - 0.14.12
  - dependency-name: moleculer-docgen
    versions:
    - 0.2.2
